"use strict";(self.webpackChunkdemo=self.webpackChunkdemo||[]).push([[56],{1439:function(c,n,e){e.r(n),e.d(n,{demos:function(){return p}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(75271),v=e(94843),p={"foo-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function u(){var a,_;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,Promise.resolve().then(e.bind(e,63330));case 2:return a=r.sent,_=a.Foo,r.abrupt("return",{default:function(){return t.createElement(_,{title:"Hello dumi!Foo"})}});case 5:case"end":return r.stop()}},u)})))),asset:{type:"BLOCK",id:"foo-demo-0",refAtomIds:["foo"],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo } from '@liangskyli/demo1';

export default () => <Foo title="Hello dumi!Foo" />;`},"@liangskyli/demo1":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo1":e(63330)},renderOpts:{compile:function(){var u=i()(o()().mark(function _(){var l,r=arguments;return o()().wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return d.next=2,e.e(760).then(e.bind(e,29760));case 2:return d.abrupt("return",(l=d.sent).default.apply(l,r));case 3:case"end":return d.stop()}},_)}));function a(){return u.apply(this,arguments)}return a}()}}}},21343:function(c,n,e){e.r(n),e.d(n,{demos:function(){return p}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(75271),v=e(37377),p={"foo2-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function u(){var a,_;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,Promise.resolve().then(e.bind(e,63330));case 2:return a=r.sent,_=a.Foo2,r.abrupt("return",{default:function(){return t.createElement(_,{title:"Hello dumi!Foo2"})}});case 5:case"end":return r.stop()}},u)})))),asset:{type:"BLOCK",id:"foo2-demo-0",refAtomIds:["foo2"],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo2 } from '@liangskyli/demo1';

export default () => <Foo2 title="Hello dumi!Foo2" />;`},"@liangskyli/demo1":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo1":e(63330)},renderOpts:{compile:function(){var u=i()(o()().mark(function _(){var l,r=arguments;return o()().wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return d.next=2,e.e(760).then(e.bind(e,29760));case 2:return d.abrupt("return",(l=d.sent).default.apply(l,r));case 3:case"end":return d.stop()}},_)}));function a(){return u.apply(this,arguments)}return a}()}}}},84582:function(c,n,e){e.r(n),e.d(n,{demos:function(){return p}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(75271),v=e(36490),p={"packages-demo-1-src-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function u(){var a,_;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,Promise.resolve().then(e.bind(e,63330));case 2:return a=r.sent,_=a.Foo,r.abrupt("return",{default:function(){return t.createElement(_,{title:"Hello dumi!Foo"})}});case 5:case"end":return r.stop()}},u)})))),asset:{type:"BLOCK",id:"packages-demo-1-src-demo-0",refAtomIds:[],dependencies:{"index.tsx":{type:"FILE",value:`import { Foo } from '@liangskyli/demo1';

export default () => <Foo title="Hello dumi!Foo" />;`},"@liangskyli/demo1":{type:"NPM",value:"0.0.0"}},entry:"index.tsx"},context:{"@liangskyli/demo1":e(63330)},renderOpts:{compile:function(){var u=i()(o()().mark(function _(){var l,r=arguments;return o()().wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return d.next=2,e.e(760).then(e.bind(e,29760));case 2:return d.abrupt("return",(l=d.sent).default.apply(l,r));case 3:case"end":return d.stop()}},_)}));function a(){return u.apply(this,arguments)}return a}()}}}},34960:function(c,n,e){e.r(n),e.d(n,{demos:function(){return s}});var m=e(75271),o=e(11813),s={}},64843:function(c,n,e){e.r(n),e.d(n,{demos:function(){return s}});var m=e(75271),o=e(18850),s={}},5905:function(c,n,e){e.r(n),e.d(n,{demos:function(){return p}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(75271),v=e(16567),p={"foo22-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function u(){var a,_;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,Promise.resolve().then(e.bind(e,16262));case 2:return a=r.sent,_=a.Foo22,r.abrupt("return",{default:function(){return t.createElement(_,{title:"Hello dumi!Foo22"})}});case 5:case"end":return r.stop()}},u)})))),asset:{type:"BLOCK",id:"foo22-demo-0",refAtomIds:["foo22"],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo22 } from '@liangskyli/demo2';

export default () => <Foo22 title="Hello dumi!Foo22" />;`},"@liangskyli/demo2":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo2":e(16262)},renderOpts:{compile:function(){var u=i()(o()().mark(function _(){var l,r=arguments;return o()().wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return d.next=2,e.e(760).then(e.bind(e,29760));case 2:return d.abrupt("return",(l=d.sent).default.apply(l,r));case 3:case"end":return d.stop()}},_)}));function a(){return u.apply(this,arguments)}return a}()}}}},95180:function(c,n,e){e.r(n),e.d(n,{demos:function(){return p}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(75271),v=e(72222),p={"packages-demo-2-src-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function u(){var a,_;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,Promise.resolve().then(e.bind(e,16262));case 2:return a=r.sent,_=a.Foo22,r.abrupt("return",{default:function(){return t.createElement(_,{title:"Hello dumi!Foo22"})}});case 5:case"end":return r.stop()}},u)})))),asset:{type:"BLOCK",id:"packages-demo-2-src-demo-0",refAtomIds:[],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo22 } from '@liangskyli/demo2';

export default () => <Foo22 title="Hello dumi!Foo22" />;`},"@liangskyli/demo2":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo2":e(16262)},renderOpts:{compile:function(){var u=i()(o()().mark(function _(){var l,r=arguments;return o()().wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return d.next=2,e.e(760).then(e.bind(e,29760));case 2:return d.abrupt("return",(l=d.sent).default.apply(l,r));case 3:case"end":return d.stop()}},_)}));function a(){return u.apply(this,arguments)}return a}()}}}},63330:function(c,n,e){e.r(n),e.d(n,{Foo:function(){return s},Foo2:function(){return v},getName:function(){return p},getName2:function(){return u}});var m=e(52676),o=function(_){return(0,m.jsx)("div",{"data-testid":"foo",className:"foo-title",children:_.title})},s=o,i=e(75271),t=function(_){return(0,m.jsx)("h4",{children:_.title})},v=t,p=function(_){var l=arguments.length>1&&arguments[1]!==void 0?arguments[1]:"default";return"".concat(_,"-").concat(l)},u=function(_){var l=arguments.length>1&&arguments[1]!==void 0?arguments[1]:"default";return"".concat(_,"-").concat(l)}},16262:function(c,n,e){e.r(n),e.d(n,{Foo22:function(){return s}});var m=e(52676),o=function(t){return(0,m.jsx)("h4",{children:t.title})},s=o},45141:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(94843);const o=[{value:"\u8BF4\u660E.",paraId:0,tocIndex:0}]},25365:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(37377);const o=[{value:"\u8BF4\u660E.",paraId:0,tocIndex:0}]},77383:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(36490);const o=[{value:"todo.",paraId:0,tocIndex:0},{value:`$ yarn add @liangskyli/demo1
`,paraId:1,tocIndex:2}]},46436:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(11813);const o=[{value:"\u83B7\u53D6\u5B8C\u6574\u540D\u5B57",paraId:0,tocIndex:0},{value:`import { getName } from '@liangskyli/demo1';

export default () => <div>{getName('name1')}</div>;
`,paraId:1,tocIndex:1},{value:"\u53C2\u6570",paraId:2,tocIndex:3},{value:"\u8BF4\u660E",paraId:2,tocIndex:3},{value:"\u7C7B\u578B",paraId:2,tocIndex:3},{value:"\u9ED8\u8BA4\u503C",paraId:2,tocIndex:3},{value:"name1",paraId:2,tocIndex:3},{value:"\u540D\u5B571",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"-",paraId:2,tocIndex:3},{value:"name2",paraId:2,tocIndex:3},{value:"\u540D\u5B572",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"default",paraId:2,tocIndex:3}]},31213:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(18850);const o=[{value:"\u83B7\u53D6\u5B8C\u6574\u540D\u5B572",paraId:0,tocIndex:0},{value:`import { getName2 } from '@liangskyli/demo1';

export default () => <div>{getName2('name2')}</div>;
`,paraId:1,tocIndex:1},{value:"\u53C2\u6570",paraId:2,tocIndex:3},{value:"\u8BF4\u660E",paraId:2,tocIndex:3},{value:"\u7C7B\u578B",paraId:2,tocIndex:3},{value:"\u9ED8\u8BA4\u503C",paraId:2,tocIndex:3},{value:"name1",paraId:2,tocIndex:3},{value:"\u540D\u5B571",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"-",paraId:2,tocIndex:3},{value:"name2",paraId:2,tocIndex:3},{value:"\u540D\u5B572",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"default",paraId:2,tocIndex:3}]},22389:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(16567);const o=[{value:"\u8BF4\u660E.",paraId:0,tocIndex:0}]},42322:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(72222);const o=[{value:"todo.",paraId:0,tocIndex:0},{value:`$ yarn add @liangskyli/demo2
`,paraId:1,tocIndex:2}]}}]);
