"use strict";(self.webpackChunkdemo=self.webpackChunkdemo||[]).push([[56],{40609:function(i,n,e){e.r(n),e.d(n,{demos:function(){return c}});var d=e(90228),t=e.n(d),f=e(87999),s=e.n(f),u=e(48222),p=e(51038),c={"foo-demo-0":{component:u.memo(u.lazy(s()(t()().mark(function _(){var l,a;return t()().wrap(function(o){for(;;)switch(o.prev=o.next){case 0:return o.next=2,Promise.resolve().then(e.bind(e,51038));case 2:return l=o.sent,a=l.Foo,o.abrupt("return",{default:function(){return u.createElement(a,{title:"Hello dumi!Foo"})}});case 5:case"end":return o.stop()}},_)})))),asset:{type:"BLOCK",id:"foo-demo-0",refAtomIds:["foo"],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo } from '@liangskyli/demo1';

export default () => <Foo title="Hello dumi!Foo" />;`},"@liangskyli/demo1":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo1":p},renderOpts:{compile:function(){var _=s()(t()().mark(function a(){var m,o=arguments;return t()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(129).then(e.bind(e,39129));case 2:return r.abrupt("return",(m=r.sent).default.apply(m,o));case 3:case"end":return r.stop()}},a)}));function l(){return _.apply(this,arguments)}return l}()}}}},78513:function(i,n,e){e.r(n),e.d(n,{demos:function(){return c}});var d=e(90228),t=e.n(d),f=e(87999),s=e.n(f),u=e(48222),p=e(51038),c={"foo2-demo-0":{component:u.memo(u.lazy(s()(t()().mark(function _(){var l,a;return t()().wrap(function(o){for(;;)switch(o.prev=o.next){case 0:return o.next=2,Promise.resolve().then(e.bind(e,51038));case 2:return l=o.sent,a=l.Foo2,o.abrupt("return",{default:function(){return u.createElement(a,{title:"Hello dumi!Foo2"})}});case 5:case"end":return o.stop()}},_)})))),asset:{type:"BLOCK",id:"foo2-demo-0",refAtomIds:["foo2"],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo2 } from '@liangskyli/demo1';

export default () => <Foo2 title="Hello dumi!Foo2" />;`},"@liangskyli/demo1":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo1":p},renderOpts:{compile:function(){var _=s()(t()().mark(function a(){var m,o=arguments;return t()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(129).then(e.bind(e,39129));case 2:return r.abrupt("return",(m=r.sent).default.apply(m,o));case 3:case"end":return r.stop()}},a)}));function l(){return _.apply(this,arguments)}return l}()}}}},396:function(i,n,e){e.r(n),e.d(n,{demos:function(){return c}});var d=e(90228),t=e.n(d),f=e(87999),s=e.n(f),u=e(48222),p=e(51038),c={"packages-demo-1-src-demo-0":{component:u.memo(u.lazy(s()(t()().mark(function _(){var l,a;return t()().wrap(function(o){for(;;)switch(o.prev=o.next){case 0:return o.next=2,Promise.resolve().then(e.bind(e,51038));case 2:return l=o.sent,a=l.Foo,o.abrupt("return",{default:function(){return u.createElement(a,{title:"Hello dumi!Foo"})}});case 5:case"end":return o.stop()}},_)})))),asset:{type:"BLOCK",id:"packages-demo-1-src-demo-0",refAtomIds:[],dependencies:{"index.tsx":{type:"FILE",value:`import { Foo } from '@liangskyli/demo1';

export default () => <Foo title="Hello dumi!Foo" />;`},"@liangskyli/demo1":{type:"NPM",value:"0.0.0"}},entry:"index.tsx"},context:{"@liangskyli/demo1":p},renderOpts:{compile:function(){var _=s()(t()().mark(function a(){var m,o=arguments;return t()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(129).then(e.bind(e,39129));case 2:return r.abrupt("return",(m=r.sent).default.apply(m,o));case 3:case"end":return r.stop()}},a)}));function l(){return _.apply(this,arguments)}return l}()}}}},56972:function(i,n,e){e.r(n),e.d(n,{demos:function(){return t}});var d=e(48222),t={}},95522:function(i,n,e){e.r(n),e.d(n,{demos:function(){return t}});var d=e(48222),t={}},42198:function(i,n,e){e.r(n),e.d(n,{demos:function(){return c}});var d=e(90228),t=e.n(d),f=e(87999),s=e.n(f),u=e(48222),p=e(15064),c={"foo22-demo-0":{component:u.memo(u.lazy(s()(t()().mark(function _(){var l,a;return t()().wrap(function(o){for(;;)switch(o.prev=o.next){case 0:return o.next=2,Promise.resolve().then(e.bind(e,15064));case 2:return l=o.sent,a=l.Foo22,o.abrupt("return",{default:function(){return u.createElement(a,{title:"Hello dumi!Foo22"})}});case 5:case"end":return o.stop()}},_)})))),asset:{type:"BLOCK",id:"foo22-demo-0",refAtomIds:["foo22"],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo22 } from '@liangskyli/demo2';

export default () => <Foo22 title="Hello dumi!Foo22" />;`},"@liangskyli/demo2":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo2":p},renderOpts:{compile:function(){var _=s()(t()().mark(function a(){var m,o=arguments;return t()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(129).then(e.bind(e,39129));case 2:return r.abrupt("return",(m=r.sent).default.apply(m,o));case 3:case"end":return r.stop()}},a)}));function l(){return _.apply(this,arguments)}return l}()}}}},58989:function(i,n,e){e.r(n),e.d(n,{demos:function(){return c}});var d=e(90228),t=e.n(d),f=e(87999),s=e.n(f),u=e(48222),p=e(15064),c={"packages-demo-2-src-demo-0":{component:u.memo(u.lazy(s()(t()().mark(function _(){var l,a;return t()().wrap(function(o){for(;;)switch(o.prev=o.next){case 0:return o.next=2,Promise.resolve().then(e.bind(e,15064));case 2:return l=o.sent,a=l.Foo22,o.abrupt("return",{default:function(){return u.createElement(a,{title:"Hello dumi!Foo22"})}});case 5:case"end":return o.stop()}},_)})))),asset:{type:"BLOCK",id:"packages-demo-2-src-demo-0",refAtomIds:[],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo22 } from '@liangskyli/demo2';

export default () => <Foo22 title="Hello dumi!Foo22" />;`},"@liangskyli/demo2":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo2":p},renderOpts:{compile:function(){var _=s()(t()().mark(function a(){var m,o=arguments;return t()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(129).then(e.bind(e,39129));case 2:return r.abrupt("return",(m=r.sent).default.apply(m,o));case 3:case"end":return r.stop()}},a)}));function l(){return _.apply(this,arguments)}return l}()}}}},51038:function(i,n,e){e.r(n),e.d(n,{Foo:function(){return f},Foo2:function(){return p},getName:function(){return c},getName2:function(){return _}});var d=e(45822),t=function(a){return(0,d.jsx)("div",{"data-testid":"foo",className:"foo-title",children:a.title})},f=t,s=e(48222),u=function(a){return(0,d.jsx)("h4",{children:a.title})},p=u,c=function(a){var m=arguments.length>1&&arguments[1]!==void 0?arguments[1]:"default";return"".concat(a,"-").concat(m)},_=function(a){var m=arguments.length>1&&arguments[1]!==void 0?arguments[1]:"default";return"".concat(a,"-").concat(m)}},15064:function(i,n,e){e.r(n),e.d(n,{Foo22:function(){return f}});var d=e(45822),t=function(u){return(0,d.jsx)("h4",{children:u.title})},f=t},94307:function(i,n,e){e.r(n),e.d(n,{texts:function(){return d}});const d=[{value:"\u8BF4\u660E.",paraId:0,tocIndex:0}]},1616:function(i,n,e){e.r(n),e.d(n,{texts:function(){return d}});const d=[{value:"\u8BF4\u660E.",paraId:0,tocIndex:0}]},72099:function(i,n,e){e.r(n),e.d(n,{texts:function(){return d}});const d=[{value:"todo.",paraId:0,tocIndex:0},{value:`$ yarn add @liangskyli/demo1
`,paraId:1,tocIndex:2}]},75083:function(i,n,e){e.r(n),e.d(n,{texts:function(){return d}});const d=[{value:"\u83B7\u53D6\u5B8C\u6574\u540D\u5B57",paraId:0,tocIndex:0},{value:`import { getName } from '@liangskyli/demo1';

export default () => <div>{getName('name1')}</div>;
`,paraId:1,tocIndex:1},{value:"\u53C2\u6570",paraId:2,tocIndex:3},{value:"\u8BF4\u660E",paraId:2,tocIndex:3},{value:"\u7C7B\u578B",paraId:2,tocIndex:3},{value:"\u9ED8\u8BA4\u503C",paraId:2,tocIndex:3},{value:"name1",paraId:2,tocIndex:3},{value:"\u540D\u5B571",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"-",paraId:2,tocIndex:3},{value:"name2",paraId:2,tocIndex:3},{value:"\u540D\u5B572",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"default",paraId:2,tocIndex:3}]},12481:function(i,n,e){e.r(n),e.d(n,{texts:function(){return d}});const d=[{value:"\u83B7\u53D6\u5B8C\u6574\u540D\u5B572",paraId:0,tocIndex:0},{value:`import { getName2 } from '@liangskyli/demo1';

export default () => <div>{getName2('name2')}</div>;
`,paraId:1,tocIndex:1},{value:"\u53C2\u6570",paraId:2,tocIndex:3},{value:"\u8BF4\u660E",paraId:2,tocIndex:3},{value:"\u7C7B\u578B",paraId:2,tocIndex:3},{value:"\u9ED8\u8BA4\u503C",paraId:2,tocIndex:3},{value:"name1",paraId:2,tocIndex:3},{value:"\u540D\u5B571",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"-",paraId:2,tocIndex:3},{value:"name2",paraId:2,tocIndex:3},{value:"\u540D\u5B572",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"default",paraId:2,tocIndex:3}]},6469:function(i,n,e){e.r(n),e.d(n,{texts:function(){return d}});const d=[{value:"\u8BF4\u660E.",paraId:0,tocIndex:0}]},1316:function(i,n,e){e.r(n),e.d(n,{texts:function(){return d}});const d=[{value:"todo.",paraId:0,tocIndex:0},{value:`$ yarn add @liangskyli/demo2
`,paraId:1,tocIndex:2}]}}]);
