"use strict";(self.webpackChunkdemo=self.webpackChunkdemo||[]).push([[56],{53551:function(c,n,e){e.r(n),e.d(n,{demos:function(){return v}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(39546),f=e(76289),p=e(87463),v={"foo-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function l(){var d,a;return o()().wrap(function(_){for(;;)switch(_.prev=_.next){case 0:return _.next=2,Promise.resolve().then(e.bind(e,87463));case 2:return d=_.sent,a=d.Foo,_.abrupt("return",{default:function(){return t.createElement(a,{title:"Hello dumi!Foo"})}});case 5:case"end":return _.stop()}},l)})))),asset:{type:"BLOCK",id:"foo-demo-0",refAtomIds:["foo"],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo } from '@liangskyli/demo1';

export default () => <Foo title="Hello dumi!Foo" />;`},"@liangskyli/demo1":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo1":p},renderOpts:{compile:function(){var l=i()(o()().mark(function a(){var u,_=arguments;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(502).then(e.bind(e,92502));case 2:return r.abrupt("return",(u=r.sent).default.apply(u,_));case 3:case"end":return r.stop()}},a)}));function d(){return l.apply(this,arguments)}return d}()}}}},86812:function(c,n,e){e.r(n),e.d(n,{demos:function(){return v}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(39546),f=e(46168),p=e(87463),v={"foo2-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function l(){var d,a;return o()().wrap(function(_){for(;;)switch(_.prev=_.next){case 0:return _.next=2,Promise.resolve().then(e.bind(e,87463));case 2:return d=_.sent,a=d.Foo2,_.abrupt("return",{default:function(){return t.createElement(a,{title:"Hello dumi!Foo2"})}});case 5:case"end":return _.stop()}},l)})))),asset:{type:"BLOCK",id:"foo2-demo-0",refAtomIds:["foo2"],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo2 } from '@liangskyli/demo1';

export default () => <Foo2 title="Hello dumi!Foo2" />;`},"@liangskyli/demo1":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo1":p},renderOpts:{compile:function(){var l=i()(o()().mark(function a(){var u,_=arguments;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(502).then(e.bind(e,92502));case 2:return r.abrupt("return",(u=r.sent).default.apply(u,_));case 3:case"end":return r.stop()}},a)}));function d(){return l.apply(this,arguments)}return d}()}}}},73216:function(c,n,e){e.r(n),e.d(n,{demos:function(){return v}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(39546),f=e(44005),p=e(87463),v={"packages-demo-1-src-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function l(){var d,a;return o()().wrap(function(_){for(;;)switch(_.prev=_.next){case 0:return _.next=2,Promise.resolve().then(e.bind(e,87463));case 2:return d=_.sent,a=d.Foo,_.abrupt("return",{default:function(){return t.createElement(a,{title:"Hello dumi!Foo"})}});case 5:case"end":return _.stop()}},l)})))),asset:{type:"BLOCK",id:"packages-demo-1-src-demo-0",refAtomIds:[],dependencies:{"index.tsx":{type:"FILE",value:`import { Foo } from '@liangskyli/demo1';

export default () => <Foo title="Hello dumi!Foo" />;`},"@liangskyli/demo1":{type:"NPM",value:"0.0.0"}},entry:"index.tsx"},context:{"@liangskyli/demo1":p},renderOpts:{compile:function(){var l=i()(o()().mark(function a(){var u,_=arguments;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(502).then(e.bind(e,92502));case 2:return r.abrupt("return",(u=r.sent).default.apply(u,_));case 3:case"end":return r.stop()}},a)}));function d(){return l.apply(this,arguments)}return d}()}}}},90850:function(c,n,e){e.r(n),e.d(n,{demos:function(){return s}});var m=e(39546),o=e(22365),s={}},75116:function(c,n,e){e.r(n),e.d(n,{demos:function(){return s}});var m=e(39546),o=e(33594),s={}},39391:function(c,n,e){e.r(n),e.d(n,{demos:function(){return v}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(39546),f=e(28391),p=e(22992),v={"foo22-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function l(){var d,a;return o()().wrap(function(_){for(;;)switch(_.prev=_.next){case 0:return _.next=2,Promise.resolve().then(e.bind(e,22992));case 2:return d=_.sent,a=d.Foo22,_.abrupt("return",{default:function(){return t.createElement(a,{title:"Hello dumi!Foo22"})}});case 5:case"end":return _.stop()}},l)})))),asset:{type:"BLOCK",id:"foo22-demo-0",refAtomIds:["foo22"],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo22 } from '@liangskyli/demo2';

export default () => <Foo22 title="Hello dumi!Foo22" />;`},"@liangskyli/demo2":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo2":p},renderOpts:{compile:function(){var l=i()(o()().mark(function a(){var u,_=arguments;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(502).then(e.bind(e,92502));case 2:return r.abrupt("return",(u=r.sent).default.apply(u,_));case 3:case"end":return r.stop()}},a)}));function d(){return l.apply(this,arguments)}return d}()}}}},88353:function(c,n,e){e.r(n),e.d(n,{demos:function(){return v}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(39546),f=e(20139),p=e(22992),v={"packages-demo-2-src-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function l(){var d,a;return o()().wrap(function(_){for(;;)switch(_.prev=_.next){case 0:return _.next=2,Promise.resolve().then(e.bind(e,22992));case 2:return d=_.sent,a=d.Foo22,_.abrupt("return",{default:function(){return t.createElement(a,{title:"Hello dumi!Foo22"})}});case 5:case"end":return _.stop()}},l)})))),asset:{type:"BLOCK",id:"packages-demo-2-src-demo-0",refAtomIds:[],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo22 } from '@liangskyli/demo2';

export default () => <Foo22 title="Hello dumi!Foo22" />;`},"@liangskyli/demo2":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo2":p},renderOpts:{compile:function(){var l=i()(o()().mark(function a(){var u,_=arguments;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(502).then(e.bind(e,92502));case 2:return r.abrupt("return",(u=r.sent).default.apply(u,_));case 3:case"end":return r.stop()}},a)}));function d(){return l.apply(this,arguments)}return d}()}}}},87463:function(c,n,e){e.r(n),e.d(n,{Foo:function(){return s},Foo2:function(){return f},getName:function(){return p},getName2:function(){return v}});var m=e(74132),o=function(d){return(0,m.jsx)("div",{"data-testid":"foo",className:"foo-title",children:d.title})},s=o,i=e(39546),t=function(d){return(0,m.jsx)("h4",{children:d.title})},f=t,p=function(d){var a=arguments.length>1&&arguments[1]!==void 0?arguments[1]:"default";return"".concat(d,"-").concat(a)},v=function(d){var a=arguments.length>1&&arguments[1]!==void 0?arguments[1]:"default";return"".concat(d,"-").concat(a)}},22992:function(c,n,e){e.r(n),e.d(n,{Foo22:function(){return s}});var m=e(74132),o=function(t){return(0,m.jsx)("h4",{children:t.title})},s=o},1235:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(76289);const o=[{value:"\u8BF4\u660E.",paraId:0,tocIndex:0}]},20573:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(46168);const o=[{value:"\u8BF4\u660E.",paraId:0,tocIndex:0}]},60432:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(44005);const o=[{value:"todo.",paraId:0,tocIndex:0},{value:`$ yarn add @liangskyli/demo1
`,paraId:1,tocIndex:2}]},81236:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(22365);const o=[{value:"\u83B7\u53D6\u5B8C\u6574\u540D\u5B57",paraId:0,tocIndex:0},{value:`import { getName } from '@liangskyli/demo1';

export default () => <div>{getName('name1')}</div>;
`,paraId:1,tocIndex:1},{value:"\u53C2\u6570",paraId:2,tocIndex:3},{value:"\u8BF4\u660E",paraId:2,tocIndex:3},{value:"\u7C7B\u578B",paraId:2,tocIndex:3},{value:"\u9ED8\u8BA4\u503C",paraId:2,tocIndex:3},{value:"name1",paraId:2,tocIndex:3},{value:"\u540D\u5B571",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"-",paraId:2,tocIndex:3},{value:"name2",paraId:2,tocIndex:3},{value:"\u540D\u5B572",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"default",paraId:2,tocIndex:3}]},95390:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(33594);const o=[{value:"\u83B7\u53D6\u5B8C\u6574\u540D\u5B572",paraId:0,tocIndex:0},{value:`import { getName2 } from '@liangskyli/demo1';

export default () => <div>{getName2('name2')}</div>;
`,paraId:1,tocIndex:1},{value:"\u53C2\u6570",paraId:2,tocIndex:3},{value:"\u8BF4\u660E",paraId:2,tocIndex:3},{value:"\u7C7B\u578B",paraId:2,tocIndex:3},{value:"\u9ED8\u8BA4\u503C",paraId:2,tocIndex:3},{value:"name1",paraId:2,tocIndex:3},{value:"\u540D\u5B571",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"-",paraId:2,tocIndex:3},{value:"name2",paraId:2,tocIndex:3},{value:"\u540D\u5B572",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"default",paraId:2,tocIndex:3}]},30587:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(28391);const o=[{value:"\u8BF4\u660E.",paraId:0,tocIndex:0}]},69601:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(20139);const o=[{value:"todo.",paraId:0,tocIndex:0},{value:`$ yarn add @liangskyli/demo2
`,paraId:1,tocIndex:2}]}}]);
