"use strict";(self.webpackChunkdemo=self.webpackChunkdemo||[]).push([[56],{37153:function(c,n,e){e.r(n),e.d(n,{demos:function(){return v}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(75271),f=e(98916),p=e(39911),v={"foo-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function l(){var d,a;return o()().wrap(function(_){for(;;)switch(_.prev=_.next){case 0:return _.next=2,Promise.resolve().then(e.bind(e,39911));case 2:return d=_.sent,a=d.Foo,_.abrupt("return",{default:function(){return t.createElement(a,{title:"Hello dumi!Foo"})}});case 5:case"end":return _.stop()}},l)})))),asset:{type:"BLOCK",id:"foo-demo-0",refAtomIds:["foo"],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo } from '@liangskyli/demo1';

export default () => <Foo title="Hello dumi!Foo" />;`},"@liangskyli/demo1":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo1":p},renderOpts:{compile:function(){var l=i()(o()().mark(function a(){var u,_=arguments;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(344).then(e.bind(e,61344));case 2:return r.abrupt("return",(u=r.sent).default.apply(u,_));case 3:case"end":return r.stop()}},a)}));function d(){return l.apply(this,arguments)}return d}()}}}},6990:function(c,n,e){e.r(n),e.d(n,{demos:function(){return v}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(75271),f=e(99523),p=e(39911),v={"foo2-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function l(){var d,a;return o()().wrap(function(_){for(;;)switch(_.prev=_.next){case 0:return _.next=2,Promise.resolve().then(e.bind(e,39911));case 2:return d=_.sent,a=d.Foo2,_.abrupt("return",{default:function(){return t.createElement(a,{title:"Hello dumi!Foo2"})}});case 5:case"end":return _.stop()}},l)})))),asset:{type:"BLOCK",id:"foo2-demo-0",refAtomIds:["foo2"],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo2 } from '@liangskyli/demo1';

export default () => <Foo2 title="Hello dumi!Foo2" />;`},"@liangskyli/demo1":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo1":p},renderOpts:{compile:function(){var l=i()(o()().mark(function a(){var u,_=arguments;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(344).then(e.bind(e,61344));case 2:return r.abrupt("return",(u=r.sent).default.apply(u,_));case 3:case"end":return r.stop()}},a)}));function d(){return l.apply(this,arguments)}return d}()}}}},71066:function(c,n,e){e.r(n),e.d(n,{demos:function(){return v}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(75271),f=e(77980),p=e(39911),v={"packages-demo-1-src-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function l(){var d,a;return o()().wrap(function(_){for(;;)switch(_.prev=_.next){case 0:return _.next=2,Promise.resolve().then(e.bind(e,39911));case 2:return d=_.sent,a=d.Foo,_.abrupt("return",{default:function(){return t.createElement(a,{title:"Hello dumi!Foo"})}});case 5:case"end":return _.stop()}},l)})))),asset:{type:"BLOCK",id:"packages-demo-1-src-demo-0",refAtomIds:[],dependencies:{"index.tsx":{type:"FILE",value:`import { Foo } from '@liangskyli/demo1';

export default () => <Foo title="Hello dumi!Foo" />;`},"@liangskyli/demo1":{type:"NPM",value:"0.0.0"}},entry:"index.tsx"},context:{"@liangskyli/demo1":p},renderOpts:{compile:function(){var l=i()(o()().mark(function a(){var u,_=arguments;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(344).then(e.bind(e,61344));case 2:return r.abrupt("return",(u=r.sent).default.apply(u,_));case 3:case"end":return r.stop()}},a)}));function d(){return l.apply(this,arguments)}return d}()}}}},16028:function(c,n,e){e.r(n),e.d(n,{demos:function(){return s}});var m=e(75271),o=e(81130),s={}},3505:function(c,n,e){e.r(n),e.d(n,{demos:function(){return s}});var m=e(75271),o=e(8380),s={}},79057:function(c,n,e){e.r(n),e.d(n,{demos:function(){return v}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(75271),f=e(77113),p=e(5385),v={"foo22-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function l(){var d,a;return o()().wrap(function(_){for(;;)switch(_.prev=_.next){case 0:return _.next=2,Promise.resolve().then(e.bind(e,5385));case 2:return d=_.sent,a=d.Foo22,_.abrupt("return",{default:function(){return t.createElement(a,{title:"Hello dumi!Foo22"})}});case 5:case"end":return _.stop()}},l)})))),asset:{type:"BLOCK",id:"foo22-demo-0",refAtomIds:["foo22"],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo22 } from '@liangskyli/demo2';

export default () => <Foo22 title="Hello dumi!Foo22" />;`},"@liangskyli/demo2":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo2":p},renderOpts:{compile:function(){var l=i()(o()().mark(function a(){var u,_=arguments;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(344).then(e.bind(e,61344));case 2:return r.abrupt("return",(u=r.sent).default.apply(u,_));case 3:case"end":return r.stop()}},a)}));function d(){return l.apply(this,arguments)}return d}()}}}},4132:function(c,n,e){e.r(n),e.d(n,{demos:function(){return v}});var m=e(90228),o=e.n(m),s=e(87999),i=e.n(s),t=e(75271),f=e(54262),p=e(5385),v={"packages-demo-2-src-demo-0":{component:t.memo(t.lazy(i()(o()().mark(function l(){var d,a;return o()().wrap(function(_){for(;;)switch(_.prev=_.next){case 0:return _.next=2,Promise.resolve().then(e.bind(e,5385));case 2:return d=_.sent,a=d.Foo22,_.abrupt("return",{default:function(){return t.createElement(a,{title:"Hello dumi!Foo22"})}});case 5:case"end":return _.stop()}},l)})))),asset:{type:"BLOCK",id:"packages-demo-2-src-demo-0",refAtomIds:[],dependencies:{"index.jsx":{type:"FILE",value:`import { Foo22 } from '@liangskyli/demo2';

export default () => <Foo22 title="Hello dumi!Foo22" />;`},"@liangskyli/demo2":{type:"NPM",value:"0.0.0"}},entry:"index.jsx"},context:{"@liangskyli/demo2":p},renderOpts:{compile:function(){var l=i()(o()().mark(function a(){var u,_=arguments;return o()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,e.e(344).then(e.bind(e,61344));case 2:return r.abrupt("return",(u=r.sent).default.apply(u,_));case 3:case"end":return r.stop()}},a)}));function d(){return l.apply(this,arguments)}return d}()}}}},39911:function(c,n,e){e.r(n),e.d(n,{Foo:function(){return s},Foo2:function(){return f},getName:function(){return p},getName2:function(){return v}});var m=e(52676),o=function(d){return(0,m.jsx)("div",{"data-testid":"foo",className:"foo-title",children:d.title})},s=o,i=e(75271),t=function(d){return(0,m.jsx)("h4",{children:d.title})},f=t,p=function(d){var a=arguments.length>1&&arguments[1]!==void 0?arguments[1]:"default";return"".concat(d,"-").concat(a)},v=function(d){var a=arguments.length>1&&arguments[1]!==void 0?arguments[1]:"default";return"".concat(d,"-").concat(a)}},5385:function(c,n,e){e.r(n),e.d(n,{Foo22:function(){return s}});var m=e(52676),o=function(t){return(0,m.jsx)("h4",{children:t.title})},s=o},87529:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(98916);const o=[{value:"\u8BF4\u660E.",paraId:0,tocIndex:0}]},94400:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(99523);const o=[{value:"\u8BF4\u660E.",paraId:0,tocIndex:0}]},384:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(77980);const o=[{value:"todo.",paraId:0,tocIndex:0},{value:`$ yarn add @liangskyli/demo1
`,paraId:1,tocIndex:2}]},25501:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(81130);const o=[{value:"\u83B7\u53D6\u5B8C\u6574\u540D\u5B57",paraId:0,tocIndex:0},{value:`import { getName } from '@liangskyli/demo1';

export default () => <div>{getName('name1')}</div>;
`,paraId:1,tocIndex:1},{value:"\u53C2\u6570",paraId:2,tocIndex:3},{value:"\u8BF4\u660E",paraId:2,tocIndex:3},{value:"\u7C7B\u578B",paraId:2,tocIndex:3},{value:"\u9ED8\u8BA4\u503C",paraId:2,tocIndex:3},{value:"name1",paraId:2,tocIndex:3},{value:"\u540D\u5B571",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"-",paraId:2,tocIndex:3},{value:"name2",paraId:2,tocIndex:3},{value:"\u540D\u5B572",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"default",paraId:2,tocIndex:3}]},81315:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(8380);const o=[{value:"\u83B7\u53D6\u5B8C\u6574\u540D\u5B572",paraId:0,tocIndex:0},{value:`import { getName2 } from '@liangskyli/demo1';

export default () => <div>{getName2('name2')}</div>;
`,paraId:1,tocIndex:1},{value:"\u53C2\u6570",paraId:2,tocIndex:3},{value:"\u8BF4\u660E",paraId:2,tocIndex:3},{value:"\u7C7B\u578B",paraId:2,tocIndex:3},{value:"\u9ED8\u8BA4\u503C",paraId:2,tocIndex:3},{value:"name1",paraId:2,tocIndex:3},{value:"\u540D\u5B571",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"-",paraId:2,tocIndex:3},{value:"name2",paraId:2,tocIndex:3},{value:"\u540D\u5B572",paraId:2,tocIndex:3},{value:"string",paraId:2,tocIndex:3},{value:"default",paraId:2,tocIndex:3}]},59444:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(77113);const o=[{value:"\u8BF4\u660E.",paraId:0,tocIndex:0}]},64628:function(c,n,e){e.r(n),e.d(n,{texts:function(){return o}});var m=e(54262);const o=[{value:"todo.",paraId:0,tocIndex:0},{value:`$ yarn add @liangskyli/demo2
`,paraId:1,tocIndex:2}]}}]);
